when:
  - event: push
    branch: main
matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3
    - 8.4
steps:
  "Test docker build":
    image: woodpeckerci/plugin-docker-buildx
    settings:
      build_args: 
        - PHPVERSION: ${PHP_VERSION}
        - PHP_VERSION: ${PHP_VERSION}
      dockerfile: ./docker/Dockerfile
      repo: registry.fourstrings.duckdns.org/hauke/citools
      dry-run: true
  "Docker build and push":
    image: woodpeckerci/plugin-docker-buildx
    settings:
      build_args: 
        - PHPVERSION: ${PHP_VERSION}
        - PHP_VERSION: ${PHP_VERSION}
      dockerfile: ./docker/Dockerfile
      repo: registry.fourstrings.duckdns.org/hauke/citools
      registry: registry.fourstrings.duckdns.org
      platforms: linux/arm64, linux/amd64
      tags: ${PHP_VERSION}